# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043c\u0435\u0442\u043a\u0430',
                'verbose_name_plural': '\u0417\u0430\u043c\u0435\u0442\u043a\u0438',
            },
        ),
    ]
