# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='comment',
            name='to_post',
            field=models.IntegerField(),
        ),
    ]
