# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170705_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
