# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170706_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
