# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170709_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='corrected_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 9, 10, 10, 13, 44413, tzinfo=utc), verbose_name='\u041e\u0442\u043a\u043e\u0440\u0440\u0435\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u043e'),
        ),
    ]
