# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170709_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_corrected',
            field=models.NullBooleanField(default=False),
        ),
    ]
